[metadata]
format.version = "1.1"

[versions]
assertj = "3.24.2"
awaitility = "4.2.0"
edc = "0.3.1"
jakarta-json = "2.0.1"
jetty-jakarta-servlet-api = "5.0.2"
junit-pioneer = "2.1.0"
jupiter = "5.10.0"
okhttp-mockwebserver = "5.0.0-alpha.11"
openTelemetry = "1.18.0"
restAssured = "5.3.2"
rsApi = "3.1.0"
testcontainers = "1.19.1"
kafkaClients = "3.6.0"
sovityext = "4.2.0"
postgres = "42.4.0"
flyway = "9.0.1"
lombok = "1.18.28"

[libraries]
edc-auth-tokenbased = { module = "org.eclipse.edc:auth-tokenbased", version.ref = "edc" }

edc-boot = { module = "org.eclipse.edc:boot", version.ref = "edc" }
edc-build-plugin = { module = "org.eclipse.edc.edc-build:org.eclipse.edc.edc-build.gradle.plugin", version.ref = "edc" }
edc-configuration-filesystem = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }

edc-connector-core = { module = "org.eclipse.edc:connector-core", version.ref = "edc" }

edc-federated-catalog-core = { module = "org.eclipse.edc:federated-catalog-core", version.ref = "edc" }
edc-federated-catalog-api = { module = "org.eclipse.edc:federated-catalog-api", version.ref = "edc" }

edc-control-plane-api-client = { module = "org.eclipse.edc:control-plane-api-client", version.ref = "edc" }
edc-control-plane-api = { module = "org.eclipse.edc:control-plane-api", version.ref = "edc" }
edc-control-plane-core = { module = "org.eclipse.edc:control-plane-core", version.ref = "edc" }
edc-control-plane-spi = { module = "org.eclipse.edc:control-plane-spi", version.ref = "edc" }

edc-data-plane-api = { module = "org.eclipse.edc:data-plane-api", version.ref = "edc" }
edc-data-plane-client = { module = "org.eclipse.edc:data-plane-client", version.ref = "edc" }
edc-data-plane-core = { module = "org.eclipse.edc:data-plane-core", version.ref = "edc" }
edc-data-plane-http = { module = "org.eclipse.edc:data-plane-http", version.ref = "edc" }
edc-data-plane-selector-api = { module = "org.eclipse.edc:data-plane-selector-api", version.ref = "edc" }
edc-data-plane-selector-client = { module = "org.eclipse.edc:data-plane-selector-client", version.ref = "edc" }
edc-data-plane-selector-core = { module = "org.eclipse.edc:data-plane-selector-core", version.ref = "edc" }
edc-data-plane-spi = { module = "org.eclipse.edc:data-plane-spi", version.ref = "edc" }
edc-data-plane-util = { module = "org.eclipse.edc:data-plane-util", version.ref = "edc" }

edc-dsp = { module = "org.eclipse.edc:dsp", version.ref = "edc" }
edc-http = { module = "org.eclipse.edc:http", version.ref = "edc" }

edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }
edc-oauth2 = { module = "org.eclipse.edc:oauth2-core", version.ref = "edc" }

edc-json-ld = { module = "org.eclipse.edc:json-ld", version.ref = "edc" }

edc-management-api = { module = "org.eclipse.edc:management-api", version.ref = "edc" }

edc-monitor-jdk-logger = { module = "org.eclipse.edc:monitor-jdk-logger", version.ref = "edc" }

edc-transfer-data-plane = { module = "org.eclipse.edc:transfer-data-plane", version.ref = "edc" }

edc-transfer-pull-http-receiver = { module = "org.eclipse.edc:transfer-pull-http-receiver", version.ref = "edc" }
edc-transfer-spi = { module = "org.eclipse.edc:transfer-spi", version.ref = "edc" }

edc-vault-filesystem = { module = "org.eclipse.edc:vault-filesystem", version.ref = "edc" }

edc-api-observability = { module = "org.eclipse.edc:api-observability", version.ref = "edc" }


edc-core-spi = { module = "org.eclipse.edc:core-spi", version.ref = "edc"}
edc-sql-core = { module = "org.eclipse.edc:sql-core", version.ref = "edc"}

edc-control-plane-sql = { module = "org.eclipse.edc:control-plane-sql", version.ref = "edc"}
edc-data-plane-instance-store-sql = { module = "org.eclipse.edc:data-plane-instance-store-sql", version.ref = "edc"}
edc-sql-pool-apache-commons = { module = "org.eclipse.edc:sql-pool-apache-commons", version.ref = "edc"}
edc-transaction-local = { module = "org.eclipse.edc:transaction-local", version.ref = "edc"}

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres"}
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway"}

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok"}

sovity-pgflyway = { module = "de.sovity.edc.ext:postgres-flyway", version.ref = "sovityext" }

jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }
jetty-jakarta-servlet-api = { module = "org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api", version.ref = "jetty-jakarta-servlet-api" }


[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
